# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :node1 do |node1|
      node1.vm.box     = "precise64"
      node1.vm.box_url = "http://files.vagrantup.com/precise64.box"
      node1.vm.network :private_network, :ip => "192.168.111.100"
  end

  config.vm.define :node2 do |node2|
      node2.vm.box = "centos64"
      node2.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"
      node2.vm.network :private_network, :ip => "192.168.111.101"
  end

  # Adjust cpus and ram
  config.vm.provider :vritualbox do |vb|
      vb.config.vm.customize ["modifyvm", :id, "--memory", "512"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
  end

  config.vm.provision :ansible do |ansible|
    # point Vagrant at the location of your playbook you want to run
    ansible.playbook = "./playbooks/setup-devserver.yml"
    ansible.inventory_file = "./playbooks/hosts"
    # Increase the verbosity when ansible runs
    #ansible.options = "-vvv"

    # the Vagrant VM will be put in this host group change this should
    # match the host group in your playbook you want to test
    # If this doesn't match the action (e.g. you are running web-servers')
    # it will skip it
    ansible.hosts = "dev-server"
  end
end
