---
### A dev server is an all-in one server
- hosts: dev-server
  user: vagrant
  sudo: True
  vars:
     is_10_up: "'$ansible_distribution_version' >= '10.04'"
     is_ubuntu: "'$ansible_distribution' == 'Ubuntu'"

     # ceph vars
     apt-key: https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc
     package_name: debian-cuttlefish

  tasks:
     - include: tasks/setup.yml
     - include: tasks/deploy.yml

  handlers:
     - include: handlers/handler.yml
